development:
  auth0_domain: dev-qb6dszkhq6iinvq2.us.auth0.com
  auth0_client_id: Z1QjSCeBkDdxapP8lRpq1Lyew63peHux
  auth0_client_secret: nMQpHumus3MXleMu0RSiHqYfrq6uPVVrVd9TWvnXprXJibGjTZdHz2dsKnwZO_AE
